# Generated by Django 5.1.4 on 2025-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottodraw',
            name='draw_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lottodraw',
            name='winning_numbers',
            field=models.CharField(max_length=255),
        ),
    ]
